<%@ Page Title="" Language="C#" MasterPageFile="~/TutionCenter.Master" AutoEventWireup="true" CodeBehind="AdminPage.aspx.cs" Inherits="TutionCenter.AdminPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Welcome To Admin Page...!</h1>
    <hr />

    <table>
        <tr>
            <td><asp:Label ID="lblSortBY" runat="server" Text="Sort By"></asp:Label></td>
        </tr>
    </table>
    <asp:DropDownList ID="DropDownList1" AppendDataBoundItems="true" runat="server" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
         <asp:ListItem value="0" Text="Select First"></asp:ListItem>
        <asp:ListItem>tbl_COURSE</asp:ListItem>
        <asp:ListItem>tbl_student</asp:ListItem>
        <asp:ListItem>tbl_tutor</asp:ListItem>
    </asp:DropDownList>
    <asp:Button ID="submit" runat="server" Text="Submit" OnClick="submit_Click" />
    <asp:GridView ID="GdCourse" runat="server" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnRowCancelingEdit="GdCourse_RowCancelingEdit" OnRowDeleting="GdCourse_RowDeleting" OnRowEditing="GdCourse_RowEditing" OnRowUpdating="GdCourse_RowUpdating">
    </asp:GridView>
    <asp:GridView ID="GdStudent" runat="server" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnRowCancelingEdit="GdStudent_RowCancelingEdit" OnRowDeleting="GdStudent_RowDeleting" OnRowEditing="GdStudent_RowEditing" OnRowUpdating="GdStudent_RowUpdating">
    </asp:GridView>
    <asp:GridView ID="GdTutor" runat="server" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnRowCancelingEdit="GdTutor_RowCancelingEdit" OnRowDeleting="GdTutor_RowDeleting" OnRowEditing="GdTutor_RowEditing" OnRowUpdating="GdTutor_RowUpdating">
    </asp:GridView>
</asp:Content>
